server:
  port: 8088
  error:
    include-stacktrace: on_param

spring:
  application:
    name: bank-app-users

  mvc:
    format:
      date: iso
      date-time: iso
      time: iso

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/realms/bank-app

